### PR TITLE
deprecate skipmissings, remove T; bump to 1.0 release

### PR DESCRIPTION
**Pull request by bkamins**
This PR prepares 1.0 release of Missings.jl.

### CODE REVIEW

**Comment by bkamins** [comment]
I kept the `skipmissings` tests, as when we redesign it it is better to keep them.

**Review by nalimilan — APPROVED** [review]

**Comment by nalimilan** [comment]
Looks good, but let's hear what @pdeffebach says.

**Comment by bkamins** [comment]
(retriggered CI to make sure it passes with DataFramesMeta 0.6.1)

**Review by pdeffebach — APPROVED** [review]

**Comment by bkamins** [comment]
Thank you! I am making a release then.

**Pull request merged**
